apiVersion: v1
kind: ServiceAccount
metadata:
  name: bsgateway-api
  namespace: bsgateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bsgateway-api
  namespace: bsgateway
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["bsgateway-secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bsgateway-api
  namespace: bsgateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bsgateway-api
subjects:
- kind: ServiceAccount
  name: bsgateway-api
  namespace: bsgateway
