apiVersion: v1
kind: Service
metadata:
  name: bsgateway-api
  namespace: bsgateway
  labels:
    app: bsgateway-api
spec:
  type: ClusterIP
  selector:
    app: bsgateway-api
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bsgateway
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: bsgateway
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
